spring.autoconfigure.exclude=\
  org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,\
  org.springframework.boot.autoconfigure.security.reactive.ReactiveSecurityAutoConfiguration,\
  org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration,\
  org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration,\
  org.springframework.cloud.netflix.eureka.EurekaClientAutoConfiguration,\
  org.springframework.cloud.netflix.eureka.config.EurekaClientConfigServerAutoConfiguration,\
  org.springframework.cloud.config.client.ConfigClientAutoConfiguration,\
  org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration

spring.datasource.url=jdbc:h2:mem:phase7testdb;DB_CLOSE_DELAY=-1
spring.cloud.config.enabled=false
spring.cloud.config.import-check.enabled=false
eureka.client.enabled=false
spring.kafka.bootstrap-servers=localhost:9999
management.endpoints.web.exposure.include=health,info,metrics,prometheus
